spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://derff.mysql.tools/derff_gradebook?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: derff_gradebook
    password: nF@5Tg34f-
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.xml
    password: nF@5Tg34f-
    user: derff_gradebook
maxUploadFileSizePlayerPhoto: 2000000